name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    name: Release on GitHub
    runs-on: ubuntu-26.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      - uses: softprops/action-gh-release@v3
        with:
          generate_release_notes: true

  publish:
    name: Publish to npm
    runs-on: ubuntu-26.04
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      - uses: actions/setup-node@v7
        with:
          node-version-file: ".node-version"
          registry-url: "https://registry.npmjs.org"
          package-manager-cache: false
      - run: npm install -g npm@latest
      - run: npm ci
      - run: npm stage publish --provenance --access public